services:
  employee-client:
    build: .
    restart: always
    ports:
      - 3000:3000
    networks:
      - employee-app_employee-service-network
networks:
  employee-app_employee-service-network:
    external: true
